Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,11 +50,14 @@ jobs:
           hugo \
             --gc \
             --minify \
-            --baseURL "${{ steps.pages.outputs.base_url }}/"          
+            --baseURL "${{ steps.pages.outputs.base_url }}/"
+      - name: Verify output folder
+        run: ls -la ./public || echo "Public folder is missing!"
+      - name: Disable Jekyll
+        run: touch ./public/.nojekyll
       - name: Upload artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-pages-artifact@v2
         with:
-          name: public
           path: ./public
 
   deploy:
@@ -63,11 +66,6 @@ jobs:
     environment:
       name: github-pages
     steps:
-      - name: Download artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: public
-          path: ./public
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v3
